# @package _global_

defaults:
  - override /model/data_preprocessing: sd_latents
  - override /model/postprocessing: sd_1_5_vae

model:
  network:
    num_input_channels: 4
  vae_embedding_name: null
  return_image: true